### ISSUE TITLE
启动端口问题

### ISSUE THREAD

**Issue by libsgh** [YuQWorks/YuQ-Mirai#23]
程序启动之后占用端口吗？如果占用能否进行自定义绑定端口

**Comment by libsgh** [comment]
群消息没问题，同样的代码私聊消息控制器里报错：
```
2020-09-14 16:24:40,548 [1;31mERROR[0;39m [36mc.i.y.m.l.Bot@[DefaultDispatcher-worker-4][0;39m - An exception was thrown under a coroutine of Bot
java.lang.IllegalArgumentException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.icecreamqaq.yuq.controller.BotReflectMethodInvoker.invoke(newController.kt:322)
	at com.icecreamqaq.yuq.controller.BotActionInvoker.invoke(newController.kt:365)
	at com.IceCreamQAQ.Yu.controller.router.NewRouterImpl.invoke(NewRouter.kt:45)
	at com.icecreamqaq.yuq.RainBot.todo(RainBot.kt:66)
	at com.icecreamqaq.yuq.RainBot.receivePrivateMessage(RainBot.kt:48)
	at com.icecreamqaq.yuq.mirai.MiraiBot$startBot$2.invokeSuspend(MiraiBot.kt:348)
	at com.icecreamqaq.yuq.mirai.MiraiBot$startBot$2.invoke(MiraiBot.kt)
	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:269)
	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
	at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:246)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:519)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:474)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:264)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories$handleIncomingPacket$1.invokeSuspend(PacketFactory.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by libsgh** [comment]
启动之后，偶尔会报错，弱弱的问一下，qq群也加不上，issue不回复...这个项目还维护吗
```
Exception in thread "Thread-11" java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at com.IceCreamQAQ.Yu.util.OkHttpWebImpl.postJSON(Web.kt:169)
	at com.IceCreamQAQ.Yu.util.Web$DefaultImpls.postJSON(Web.kt:34)
	at com.IceCreamQAQ.Yu.util.OkHttpWebImpl.postJSON(Web.kt:75)
	at com.icecreamqaq.yuq.mirai.MiraiBot$start$1.run(MiraiBot.kt:225)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by IceCream-Open** [comment]
> 启动之后，偶尔会报错，弱弱的问一下，qq群也加不上，issue不回复...这个项目还维护吗
> 
> ```
> Exception in thread "Thread-11" java.net.SocketTimeoutException: connect timed out
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
> 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
> 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195)
> 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
> 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
> 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
> 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
> 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
> 	at com.IceCreamQAQ.Yu.util.OkHttpWebImpl.postJSON(Web.kt:169)
> 	at com.IceCreamQAQ.Yu.util.Web$DefaultImpls.postJSON(Web.kt:34)
> 	at com.IceCreamQAQ.Yu.util.OkHttpWebImpl.postJSON(Web.kt:75)
> 	at com.icecreamqaq.yuq.mirai.MiraiBot$start$1.run(MiraiBot.kt:225)
> 	at java.lang.Thread.run(Thread.java:748)
> ```

这个保存是因为 YuQ 的统计中心服务被关闭掉了，启动时和启动后每十分钟会出现一次，不影响使用。

**Comment by IceCream-Open** [comment]
> 程序启动之后占用端口吗？如果占用能否进行自定义绑定端口

程序启动不主动占用任何端口。当然如果你引入了 WebCore，那可能会占用配置的 Web Server 端口。

**Comment by IceCream-Open** [comment]
> 群消息没问题，同样的代码私聊消息控制器里报错：
> 
> ```
> 2020-09-14 16:24:40,548 �[1;31mERROR�[0;39m �[36mc.i.y.m.l.Bot@[DefaultDispatcher-worker-4]�[0;39m - An exception was thrown under a coroutine of Bot
> java.lang.IllegalArgumentException: null
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.icecreamqaq.yuq.controller.BotReflectMethodInvoker.invoke(newController.kt:322)
> 	at com.icecreamqaq.yuq.controller.BotActionInvoker.invoke(newController.kt:365)
> 	at com.IceCreamQAQ.Yu.controller.router.NewRouterImpl.invoke(NewRouter.kt:45)
> 	at com.icecreamqaq.yuq.RainBot.todo(RainBot.kt:66)
> 	at com.icecreamqaq.yuq.RainBot.receivePrivateMessage(RainBot.kt:48)
> 	at com.icecreamqaq.yuq.mirai.MiraiBot$startBot$2.invokeSuspend(MiraiBot.kt:348)
> 	at com.icecreamqaq.yuq.mirai.MiraiBot$startBot$2.invoke(MiraiBot.kt)
> 	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:269)
> 	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
> 	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
> 	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
> 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
> 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
> 	at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
> 	at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:246)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:519)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:474)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:264)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories$handleIncomingPacket$1.invokeSuspend(PacketFactory.kt)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> ```

这个能提供更详细的信息吗

**Comment by libsgh** [comment]
> > 群消息没问题，同样的代码私聊消息控制器里报错：
> > ```
> > 2020-09-14 16:24:40,548 �[1;31mERROR�[0;39m �[36mc.i.y.m.l.Bot@[DefaultDispatcher-worker-4]�[0;39m - An exception was thrown under a coroutine of Bot
> > java.lang.IllegalArgumentException: null
> > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > 	at java.lang.reflect.Method.invoke(Method.java:498)
> > 	at com.icecreamqaq.yuq.controller.BotReflectMethodInvoker.invoke(newController.kt:322)
> > 	at com.icecreamqaq.yuq.controller.BotActionInvoker.invoke(newController.kt:365)
> > 	at com.IceCreamQAQ.Yu.controller.router.NewRouterImpl.invoke(NewRouter.kt:45)
> > 	at com.icecreamqaq.yuq.RainBot.todo(RainBot.kt:66)
> > 	at com.icecreamqaq.yuq.RainBot.receivePrivateMessage(RainBot.kt:48)
> > 	at com.icecreamqaq.yuq.mirai.MiraiBot$startBot$2.invokeSuspend(MiraiBot.kt:348)
> > 	at com.icecreamqaq.yuq.mirai.MiraiBot$startBot$2.invoke(MiraiBot.kt)
> > 	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:269)
> > 	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
> > 	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
> > 	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
> > 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
> > 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
> > 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
> > 	at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
> > 	at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:246)
> > 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:519)
> > 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:474)
> > 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
> > 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:264)
> > 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories$handleIncomingPacket$1.invokeSuspend(PacketFactory.kt)
> > 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> > 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> > 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> > 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> > 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> > 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> > ```
> 
> 这个能提供更详细的信息吗

这个我已经知道问题了，因为我在@PrivateController的参数里面加了group就会出现这个错误，我把@PrivateController，和@BotGroupController在同一类里面使用，然后根据group判断是私聊的消息还是群消息，如果是群消息我加上at。但是发现不行，message里面也没有可以判断消息类型的东西，所以现在是分开的controller，还一个问题偶尔私聊消息yuq收不到，去mirai的issue看了下，可能是mirai的问题，mirai的核心包可以升级到新版嘛。
如何正确的发送私聊消息？我摸索了一下，感觉不是很优雅
```
//这种必须好友才行吧，如果是群里私聊的消息不可以
yuq.getFriends().get(qq).sendMessage("");
yuq.getGroups().get(group).sendMessage("");
//虽然可以发，但是方法过时了
Message message = new Message();
message.setQq(qq);
message.plus(msg);
yuq.sendMessage(msg);
//继承QQController
reply();
//在controller直接返回Message
```
