### ISSUE TITLE
I can't start the bot

### ISSUE THREAD

**Issue by shenshaoming** [YuQWorks/YuQ-Mirai#8]
`
2020-08-07 18:50:09,634 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: MiraiMessageItemFactory.

2020-08-07 18:50:09,634 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: MiraiMessageItemFactory Success!

2020-08-07 18:50:09,634 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: JobManager.

2020-08-07 18:50:09,634 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: JobManager Error!

kotlin.UninitializedPropertyAccessException: lateinit property syncTimers has not been initialized
	
at com.IceCreamQAQ.Yu.job.JobManager.stop(JobManager.kt:112)
	
at com.IceCreamQAQ.Yu.as.AsLoader.stop(AsLoader.kt:67)
	
at com.IceCreamQAQ.Yu.DefaultApp$1.run(DefaultApp.kt:37)
	
at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by IceCream-Open** [comment]
上面应该还有一段异常，请补全。

**Comment by shenshaoming** [comment]
`2020-08-10 11:58:06,622 INFO  c.i.y.m.l.Bot@[main] - Login successful
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.icecreamqaq.yuq.mirai.YuQMiraiStart$Companion.start(YuQMiraiStart.kt:29)
	at com.icecreamqaq.yuq.mirai.YuQMiraiStart$Companion.start(YuQMiraiStart.kt:47)
	at com.icecreamqaq.yuq.mirai.YuQMiraiStart.start(YuQMiraiStart.kt)
	at wiki.IceCream.yuq.demo.Start.main(Start.java:13)
Caused by: java.lang.IllegalAccessError: class jdk.internal.reflect.MethodAccessorImpl loaded by com.IceCreamQAQ.Yu.loader.AppClassloader @1fa268de cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.IceCreamQAQ.Yu.loader.AppClassloader.loadAppClass(AppClassloader.java:101)
	at com.IceCreamQAQ.Yu.loader.AppClassloader.loadClass(AppClassloader.java:64)
	at com.IceCreamQAQ.Yu.loader.AppClassloader.loadClass(AppClassloader.java:52)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/jdk.internal.misc.Unsafe.defineClass0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1192)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.alibaba.fastjson.util.FieldInfo.get(FieldInfo.java:544)
	at com.alibaba.fastjson.serializer.FieldSerializer.getPropertyValueDirect(FieldSerializer.java:149)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:293)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:324)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:461)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:745)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:683)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:648)
	at com.IceCreamQAQ.Yu.FunKt.toJSONString(fun.kt:12)
	at com.icecreamqaq.yuq.mirai.MiraiBot.registerCookie(MiraiBot.kt:161)
	at com.icecreamqaq.yuq.mirai.MiraiBot.init(MiraiBot.kt:137)
	at com.IceCreamQAQ.Yu.as.AsLoader.load(AsLoader.kt:42)
	at com.IceCreamQAQ.Yu.loader.AppLoader.load(AppLoader.kt:86)
	at com.IceCreamQAQ.Yu.DefaultApp.start(DefaultApp.kt:42)
	... 8 more
2020-08-10 11:58:06,727 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: WebHelperBeanFactory.
2020-08-10 11:58:06,728 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: WebHelperBeanFactory Success!
2020-08-10 11:58:06,728 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: EhcacheHelpFactory.
2020-08-10 11:58:06,731 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: EhcacheHelpFactory Success!
2020-08-10 11:58:06,731 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: MiraiBot.
2020-08-10 11:58:06,781 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: MiraiBot Success!
2020-08-10 11:58:06,781 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: MiraiMessageItemFactory.
2020-08-10 11:58:06,782 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: MiraiMessageItemFactory Success!
2020-08-10 11:58:06,782 INFO  c.I.Y.a.AsLoader@[Thread-0] - Stop ApplicationService: JobManager.`

**Comment by shenshaoming** [comment]
有点难搞了，原来是服务器上的电脑不行。服务器系统是Windows Server 2012
